[package]
name = "Rust_Scan"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.9"
error-chain = "0.12.4"
tokio = { version = "1.2.0", features = ["full"] }
url = "2.2.2"
